### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by Bahatte** [dev-lu/osint_toolkit#12]
Hello... i have a problem and dont know how to solve it... i tried to change docker-compose.yml but it does not work:

version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://10.99.199.12:8000  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

![image](https://github.com/dev-lu/osint_toolkit/assets/116437442/0b88cf5d-9901-4a3f-bf25-a3abccbb3483)

**Comment by dev-lu** [comment]
Please try the following compose file:

```yaml
version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://10.99.199.12:8000  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

```

**Comment by Bahatte** [comment]
nope still the same error?

**Comment by dev-lu** [comment]
Please clone the repository again. There was an error when passing the backend URL to the container. It should work now.

**Comment by Bahatte** [comment]
Hello again. The problem is still the same with a new cloned repository.

**Comment by ne0x86** [comment]
Same errors here :(

**Comment by suleimanfarouk** [comment]
I just rebuild the images and started the containers but still having the same error.

**Comment by dev-lu** [comment]
Please have a look into your browser console to see where the frontend is trying to connect to.

**Comment by ne0x86** [comment]
xhr.js:220  
 GET http://localhost:3000/api/apikeys/is_active net::ERR_CONNECTION_REFUSED 
xhr.js:220  
 GET http://localhost:3000/api/settings/modules/ net::ERR_CONNECTION_REFUSED 
172.20.0.70/:1 Uncaught (in promise)  
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …} 
xhr.js:220  
 GET http://localhost:3000/api/settings/general/ net::ERR_CONNECTION_REFUSED 
xhr.js:220  
 GET http://localhost:3000/api/settings/modules/newsfeed/ net::ERR_CONNECTION_REFUSED 
172.20.0.70/:1 Uncaught (in promise)  
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …} 
code 
:  
"ERR_NETWORK" 
config 
:  
{transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …} 
message 
:  
"Network Error" 
name 
:  
"AxiosError" 
request 
:  
XMLHttpRequest {data: undefined, onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, …} 
response 
:  
XMLHttpRequest {data: undefined, onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, …} 
[[Prototype]] 
:  
Error


172.20.0.70 is docker host ip

**Comment by dev-lu** [comment]
Did you uncomment the argument section for the backend URL in your Docker Compose file? It should look like this for you:

```yaml
version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://172.20.0.70  # Backend URL without trailing slash
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
```

**Comment by ne0x86** [comment]
Still not working. Same error but with 172.20.0.70 ip

**Comment by Bahatte** [comment]
Thanks a lot it works for me...  ill close the issue. Thanks a lot for quick help!

![image](https://github.com/dev-lu/osint_toolkit/assets/116437442/2fcb61ad-f79f-4331-a01b-43e1b903aeaf)
